name: Frontend CI

on:
  pull_request:
  push:
    branches:
      - main
      - pipeline-frontend # kan fjernes senere

jobs:
  statiske-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm" # caching for hurtigere pipeline

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run Prettier (check only)
        run: npm run format:check

  build-frontend:
    runs-on: ubuntu-latest
    needs: statiske-tests # kører kun hvis statiske-tests passer

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm" # caching for hurtigere pipeline

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js project # Kan godt være vi skal tilføje env variabler her senere, også i github actions secrets
        run: npm run build
